tosca_definitions_version: tosca_simple_yaml_1_0

topology_template:
  node_templates:
    Workstation:
      type: tosca.nodes.Compute
      attributes:
        private_address: localhost
        public_address: localhost
  
  policies:
    custom_test:
      type: radon.policies.custom.ShellScript
      properties:
        path: 'ctt/customscript.sh'

    endpoint_test:
      type: radon.policies.testing.HttpEndpoint
      properties:
        use_https:
        method: GET
        hostname: cloudstash.io
        port:
        path: /publicrepositories?repoType=Function
        expected_status: