version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: pack python folder
          command: |
            zip metaupload.zip metaupload.py
            mkdir /tmp/resources
            mv playbooks/aws_role/policy.json /tmp/resources
            mv metaupload.zip /tmp/resources
      - persist_to_workspace:
          root: /tmp/resources
          paths:
            - policy.json
            - metaupload.zip

  deploy:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/resources
      - run:
          name: install dependencies
          command: |
            sudo pip install -r requirements.txt
      - run:
          name: deploy
          command: |
            opera deploy demo demo_use_case.yml

  test:
    docker:
      - image: circleci/python:3.7.2
    environment:
      DATA_PROJ: '{"file": "none", "repository_url": "https://github.com/naesheim/use-case-radon-demo.git", "servicetemplate_location": "ctt/test_config.yml"}'
      DATA_ARTI: '{"projectId": 1}'
      DATA_DEP: '{"testartifactId": 1}'
      DATA_EXE: '{"deploymentId": 1}'
      TEST_FILE: "/home/circleci/project/ctt/test-app.zip"
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            sudo pip3 install awscli
      - run:
          name: start test environment
          command: |
             git clone https://github.com/duelle/CTT.git radon-ctt
             cd radon-ctt/cct-server
             python3 -m venv venv
             . venv/bin/activate .
             pip3 install -r requirements.txt
             python3 -m openapi_server
          background: true
      - run:
          name: create project
          command: |
            sleep 10 && echo "ok 1"
      - run:
          name: create testartifact
          command: |
            echo "ok 2"
      - run:
          name: create deployment
          command: |
            echo "ok 3"
      - run:
          name: execute test
          command: |
            echo "ok 4"
      - store_artifacts:
          path: /tmp/RadonCTT/projects/1/results

workflows:
  version: 2

  build-test-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
      - test:
          requires:
            - deploy
