version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: pack python folder
          command: |
            zip metaupload.zip metaupload.py
            mkdir /tmp/resources
            mv playbooks/aws_role/policy.json /tmp/resources
            mv metaupload.zip /tmp/resources
      - persist_to_workspace:
          root: /tmp/resources
          paths:
            - policy.json
            - metaupload.zip

  deploy:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/resources
      - run:
          name: install dependencies
          command: |
            sudo pip3 install boto3
            sudo pip3 install git+https://github.com/ansible/ansible.git@devel
            sudo pip3 install opera
      - run:
          name: deploy
          command: |
            opera deploy metahandler demo_use_case.yml

  # test:
  #   docker:
  #     - image: circleci/python:3.7.2
  #   environment:
  #     IMAGE: setter.jpg
  #   steps:
  #     - run:
  #         name: install dependencies
  #         command: |
  #           sudo pip3 install awscli
  #     - run:
  #         name: upload image to s3
  #         command: |
  #           curl https://www.dogsnsw.org.au/media/img/BrowseAllBreed//Irish-Setter.jpg > $IMAGE
  #           aws s3 mv $IMAGE s3://radon-thumbnail
  #     - run:
  #         name: verify content
  #         command: |
  #           sleep 8s
  #           aws s3 ls radon-thumbnail-resized
      
workflows:
  version: 2

  build-test-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
      # - test:
      #     requires:
      #       - deploy