- hosts: all
  gather_facts: no
  tasks:
    - name: upload-trigger
      s3_bucket_notification:
        state: present
        event_name: "{{ event_name }}"
        bucket_name: "{{ bucket_name }}"
        lambda_function_arn: "{{ lambda_function_arn }}"
        events:  [ "{{ events }}" ]
        region: "{{ region }}"